##
## Makefile for Seedbox quadlet
##

DEPENDENCIES = traefik samba

# Seedbox quadlet is mapped to the 10017 user (seedbox) and 10000 group (itix-svc)
PROJECT_UID = 10017
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
