##
## Makefile for Vsftpd quadlet
##

DEPENDENCIES = lego

# Vsftpd quadlet is mapped to the 10015 user (vsftpd) and 10000 group (itix-svc)
PROJECT_UID = 10015
PROJECT_GID = 10000

# Include common Makefile
TOP_LEVEL_DIR := ..
include $(TOP_LEVEL_DIR)/common.mk


