server string = Seedbox

[media]
path = /data/storage/media
comment = Media
valid users = @itix
write list = @itix
group = itix
directory mask = 0775
create mask = 0664

[downloads]
path = /data/storage/downloads
comment = Downloads
valid users = @itix
write list = @itix
group = itix
directory mask = 0775
create mask = 0664

[import]
path = /data/storage/import
comment = Imports
valid users = @itix
write list = @itix
group = itix
directory mask = 0775
create mask = 0664
