[global]
workgroup = ITIX
passdb backend = tdbsam:/var/lib/samba/private/sam.tdb
map to guest = Bad User
load printers = no
private dir = /var/lib/samba/private
disable netbios = yes
debug syslog format = always
