# Network parameters
pasv_address=storage.example.tld
pasv_addr_resolve=YES

# Authenticate local users
local_enable=YES
local_root=/data
chroot_local_user=YES
pam_service_name=vsftpd

# Enable write on the FTP server
write_enable=YES

# Since /var/lib/virtiofs/data (/data) is writable only by root we can allow this
allow_writeable_chroot=YES

# No anonymous access
anonymous_enable=NO

# Misc parameters
delete_failed_uploads=NO
ftpd_banner=Storage
file_open_mode=0660
ls_recurse_enable=YES
