http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud`)"
      entryPoints:
      - http
      #- https
      middlewares:
      service: "nextcloud"
      #tls:
      #  certResolver: le
  services:
    nextcloud:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:8080"
