# Network parameters
listen=YES
listen_port=21
pasv_min_port=20000
pasv_max_port=20100
pasv_enable=YES
pasv_promiscuous=YES

# Be strict by default
anonymous_enable=NO
guest_enable=NO
local_enable=NO

# Log file
vsftpd_log_file=/var/log/vsftpd/vsftpd.log
xferlog_enable=YES
syslog_enable=NO

# Misc parameters
setproctitle_enable=YES
reverse_lookup_enable=NO
