d /var/lib/quadlets/matrix/tuwunel 0700 10031 10000 -
d /var/lib/quadlets/matrix/tuwunel/db 0700 10031 10000 -
d /var/lib/quadlets/matrix/tuwunel/backup-staging 0700 10031 10000 -
d /run/quadlets/matrix/matrix-init 0700 10031 10000 -
d$ /var/lib/virtiofs/data/matrix 0700 10031 10000 -
d$ /var/lib/virtiofs/data/matrix/tuwunel 0700 10031 10000 -
d$ /var/lib/virtiofs/data/matrix/tuwunel/media 0700 10031 10000 -
d$ /var/lib/virtiofs/data/matrix/tuwunel/backup 0700 10031 10000 -
