##
## Makefile for smtprelay quadlet
##

DEPENDENCIES = lego

# smtprelay quadlet is mapped to the 10030 user (smtprelay) and 10000 group (itix-svc)
PROJECT_UID = 10030
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
