[Container]
# When in development mode, it is not possible to renew a certificate from Let's Encrypt, so we just skip the entrypoint.
Entrypoint=/bin/true

[Service]
# And we update the self-signed certificate and flag it as renewed.
ExecStartPost=/etc/quadlets/lego/lego-dev.sh
