##
## Makefile for Miniflux quadlet
##

DEPENDENCIES = postgresql traefik

# Miniflux quadlet is mapped to the 10010 user (miniflux) and 10000 group (itix-svc)
PROJECT_UID = 10010
PROJECT_GID = 10000

TOP_LEVEL_DIR := ..
include $(TOP_LEVEL_DIR)/common.mk

