d$ /run/quadlets/vsftpd 0700 0 0 -
d$ /run/quadlets/vsftpd/cache 0700 0 0 -
d$ /run/quadlets/vsftpd/tls 0700 0 0 -
d$ /var/lib/virtiofs/data/storage 0755 0 0 -
d$ /var/lib/quadlets/vsftpd/log 0755 0 0 -
d$ /var/lib/quadlets/vsftpd/data 0755 0 0 -
