##
## Makefile for Vaultwarden quadlet
##

DEPENDENCIES = postgresql traefik

# Vaultwarden quadlet is mapped to the 10020 user (vaultwarden) and 10000 group (itix-svc)
PROJECT_UID = 10020
PROJECT_GID = 10000

TOP_LEVEL_DIR := ..
include $(TOP_LEVEL_DIR)/Makefile.common

