##
## Makefile for Keycloak quadlet
##

DEPENDENCIES = postgresql traefik

# Keycloak quadlet is mapped to the 10007 user (keycloak) and 10000 group (itix-svc)
PROJECT_UID = 10007
PROJECT_GID = 10000

TOP_LEVEL_DIR := ..
include $(TOP_LEVEL_DIR)/Makefile.common

