http:
  routers:
    prowlarr:
      rule: "Host(`prowlarr`)"
      entryPoints:
      - http
      middlewares:
      service: "prowlarr"
  services:
    prowlarr:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:9696"
