http:
  routers:
    qbittorrent-webui:
      rule: "Host(`qbittorrent`)"
      entryPoints:
      - http
      middlewares:
      service: "qbittorrent-webui"
  services:
    qbittorrent-webui:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:8080"
