http:
  routers:
    radarr:
      rule: "Host(`radarr`)"
      entryPoints:
      - http
      middlewares:
      service: "radarr"
  services:
    radarr:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:7878"
