##
## Makefile for Traefik quadlet
##

# Traefik quadlet is mapped to the 10001 user (traefik) and 10000 group (itix-svc)
PROJECT_UID = 10001
PROJECT_GID = 10000

TOP_LEVEL_DIR := ..
include $(TOP_LEVEL_DIR)/Makefile.common

