##
## Makefile for Vaultwarden quadlet
##

DEPENDENCIES = postgresql traefik

# Vaultwarden quadlet is mapped to the 10020 user (vaultwarden) and 10000 group (itix-svc)
PROJECT_UID = 10020
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
