##
## Makefile for Unifi Network Application quadlet
##

# Unifi quadlet is mapped to the 10011 user (unifi) and 10000 group (itix-svc)
PROJECT_UID = 10011
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
