# Runtime directories for Quay
d /run/quadlets/quay 0755 10026 10000 -
d /run/quadlets/quay/tls 0700 10026 10000 -
# Persistent data directories for Quay
d /var/lib/virtiofs/data/quay 0700 10026 10000 -
d /var/lib/virtiofs/data/quay/redis 0700 10026 10000 -
d /var/lib/virtiofs/data/quay/storage 0700 10026 10000 -
