http:
  routers:
    traefik-ping:
      rule: Host(`ping`)
      entryPoints:
      - http
      service: "ping@internal"
      middlewares:
      - localhost-only
  middlewares:
    localhost-only:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
