# Network parameters
pasv_address=storage.example.tld
pasv_addr_resolve=YES

# Authenticate virtual users
guest_enable=YES
guest_username=vsftpd
local_enable=YES
virtual_use_local_privs=YES
chroot_local_user=YES
pam_service_name=vsftpd-virtual

# Site specific config (example)
local_root=/data
# OR
#user_sub_token=$USER
#local_root=/data/$USER

