DATABASE_URL=postgres://miniflux:miniflux@localhost/miniflux?sslmode=disable
PORT=8080
#HTTPS=1
BASE_URL=http://miniflux/
RUN_MIGRATIONS=1
CREATE_ADMIN=1
ADMIN_USERNAME=admin
ADMIN_PASSWORD=miniflux
HTTP_CLIENT_TIMEOUT=120
