APP_NAME = Gitea
RUN_USER = git
RUN_MODE = prod

[oauth2]
; OAuth2 authentication secret for access and refresh tokens, change this a unique string
;JWT_SECRET = 

[security]
; Secret used to validate communication within Gitea binary. random at every install if no uri set.
;INTERNAL_TOKEN = 
INSTALL_LOCK   = true
; Global secret key. random at every install.
;SECRET_KEY     = 

[database]
DB_TYPE  = postgres
HOST     = 127.0.0.1:5432
NAME     = gitea
USER     = gitea
PASSWD   = gitea
SSL_MODE = disable
CHARSET  = utf8
; SQL logs are rarely helpful unless we specifically ask for them
LOG_SQL  = false

[server]
APP_DATA_PATH           = /data
SSH_DOMAIN              = gitea
DOMAIN                  = gitea
HTTP_PORT               = 3000
ROOT_URL                = http://gitea/
DISABLE_SSH             = false
START_SSH_SERVER        = true
LFS_START_SERVER        = true
; LFS authentication secret, change this to a unique string
;LFS_JWT_SECRET          = 
OFFLINE_MODE            = true
PROTOCOL                = http
BUILTIN_SSH_SERVER_USER = git
SSH_LISTEN_PORT         = 2222
SSH_PORT                = 22
ENABLE_PPROF            = false

[mailer]
;ENABLED = true
;HOST    = smtp.gmail.com:587
;FROM    = 
;USER    = 
;PASSWD  = 

[service]
REGISTER_EMAIL_CONFIRM            = true
ENABLE_NOTIFY_MAIL                = true
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
;NO_REPLY_ADDRESS                  = itix.fr

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[session]
PROVIDER = file

[log]
MODE              = console
LEVEL             = warn
ENABLE_ACCESS_LOG = true
COLORIZE          = false
STDERR            = true
ROUTER            = console

[log.sublogger.access]
MODE      = file
ROOT_PATH = /data/log

[log.sublogger.macaron]
MODE      = file
FILE_NAME = /dev/null

[log.console]
MODE     = console
COLORIZE = false
STDERR   = true

[cron]
ENABLED      = true
RUN_AT_START = true

[cron.update_mirrors]
SCHEDULE = @every 24h

[mirror]
DEFAULT_INTERVAL = 24h
MIN_INTERVAL     = 30m

[app_name]
APP_NAME = Gitea

[repository]
ROOT = /data/git/gitea-repositories

[metrics]
ENABLED = false
