##
## Makefile for Gitea quadlet
##

DEPENDENCIES = postgresql traefik

# Gitea quadlet is mapped to the 10009 user (gitea) and 10000 group (itix-svc)
PROJECT_UID = 10009
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
