##
## Makefile for ntfy quadlet
##

DEPENDENCIES = postgresql traefik

# ntfy quadlet is mapped to the 10027 user (ntfy) and 10000 group (itix-svc)
PROJECT_UID = 10027
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
