##
## Makefile for Quay Container Registry quadlet
##

# Quay quadlet is mapped to the 10026 user (quay) and 10000 group (itix-svc)
PROJECT_UID = 10026
PROJECT_GID = 10000

DEPENDENCIES = postgresql lego nftables

# Include common Makefile
include ../../scripts/common.mk
