##
## Makefile for Home Assistant quadlet
##

DEPENDENCIES = postgresql traefik

# Home Assistant quadlet is mapped to the 10034 user (home-assistant) and 10000 group (itix-svc)
PROJECT_UID = 10034
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
