api:
  dashboard: false
  debug: false
ping:
  manualRouting: true

log:
  level: "INFO"

accesslog: false

global:
  sendanonymoususage: false
  checknewversion: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/conf.d/
    watch: true

# certificatesResolvers:
#   le:
#     acme:
#       email: "foo@example.test"
#       keyType: "EC384"
#       httpChallenge:
#         entryPoint: http
#       storage: "/var/lib/traefik/acme.json"
