[Container]
# When in development mode, it is not possible to get a certificate from Let's Encrypt, so we just skip the entrypoint.
Entrypoint=/bin/true

[Service]
# And we create a self-signed certificate for localhost, so that other services can still use it.
ExecStartPost=/etc/quadlets/lego/lego-dev.sh
