##
## Makefile for LiteLLM quadlet
##

DEPENDENCIES = postgresql traefik

# LiteLLM quadlet is mapped to the 10024 user (litellm) and 10000 group (itix-svc)
PROJECT_UID = 10024
PROJECT_GID = 10000

# Include common Makefile
include ../../scripts/common.mk
